name: GovOps
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.11.5
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - -r requirements.txt
      - -r pathfinder/requirements.txt
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - appdirs==1.4.4
      - attrs==24.3.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - click==8.1.8
      - datasets==3.2.0
      - dill==0.3.8
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - idna==3.10
      - iniconfig==2.0.0
      - jinja2==3.1.5
      - joblib==1.4.2
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - networkx==3.4.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==24.2
      - pillow==11.1.0
      - pluggy==1.5.0
      - propcache==0.2.1
      - psutil==6.1.1
      - pyarrow==18.1.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - requests==2.32.3
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - six==1.17.0
      - sniffio==1.3.1
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - torch==2.5.1
      - tqdm==4.67.1
      - triton==3.1.0
      - urllib3==2.3.0
      - xxhash==3.5.0
      - yarl==1.18.3
